/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const ContactSubmission = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : Time,
  'phone' : IDL.Text,
});
export const LoanType = IDL.Variant({
  'other' : IDL.Null,
  'auto' : IDL.Null,
  'home' : IDL.Null,
  'education' : IDL.Null,
  'personal' : IDL.Null,
  'business' : IDL.Null,
});
export const LoanApplication = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'loanType' : LoanType,
  'message' : IDL.Text,
  'timestamp' : Time,
  'phone' : IDL.Text,
  'amount' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAllContactSubmissions' : IDL.Func(
      [],
      [IDL.Vec(ContactSubmission)],
      ['query'],
    ),
  'getAllLoanApplications' : IDL.Func(
      [],
      [IDL.Vec(LoanApplication)],
      ['query'],
    ),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getContactSubmission' : IDL.Func([IDL.Nat], [ContactSubmission], ['query']),
  'getContactSubmissionCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getLoanApplication' : IDL.Func([IDL.Nat], [LoanApplication], ['query']),
  'getLoanApplicationCountByType' : IDL.Func([LoanType], [IDL.Nat], ['query']),
  'getLoanApplicationsByEmail' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(LoanApplication)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'searchContactSubmissionsByName' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(ContactSubmission)],
      ['query'],
    ),
  'submitContactForm' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Record({ 'id' : IDL.Nat, 'timestamp' : Time })],
      [],
    ),
  'submitLoanApplication' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, LoanType, IDL.Nat, IDL.Text],
      [IDL.Record({ 'id' : IDL.Nat, 'timestamp' : Time })],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const ContactSubmission = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : Time,
    'phone' : IDL.Text,
  });
  const LoanType = IDL.Variant({
    'other' : IDL.Null,
    'auto' : IDL.Null,
    'home' : IDL.Null,
    'education' : IDL.Null,
    'personal' : IDL.Null,
    'business' : IDL.Null,
  });
  const LoanApplication = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'loanType' : LoanType,
    'message' : IDL.Text,
    'timestamp' : Time,
    'phone' : IDL.Text,
    'amount' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAllContactSubmissions' : IDL.Func(
        [],
        [IDL.Vec(ContactSubmission)],
        ['query'],
      ),
    'getAllLoanApplications' : IDL.Func(
        [],
        [IDL.Vec(LoanApplication)],
        ['query'],
      ),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getContactSubmission' : IDL.Func(
        [IDL.Nat],
        [ContactSubmission],
        ['query'],
      ),
    'getContactSubmissionCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getLoanApplication' : IDL.Func([IDL.Nat], [LoanApplication], ['query']),
    'getLoanApplicationCountByType' : IDL.Func(
        [LoanType],
        [IDL.Nat],
        ['query'],
      ),
    'getLoanApplicationsByEmail' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(LoanApplication)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'searchContactSubmissionsByName' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(ContactSubmission)],
        ['query'],
      ),
    'submitContactForm' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Record({ 'id' : IDL.Nat, 'timestamp' : Time })],
        [],
      ),
    'submitLoanApplication' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, LoanType, IDL.Nat, IDL.Text],
        [IDL.Record({ 'id' : IDL.Nat, 'timestamp' : Time })],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };