/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ContactSubmission {
  'name' : string,
  'email' : string,
  'message' : string,
  'timestamp' : Time,
  'phone' : string,
}
export interface LoanApplication {
  'name' : string,
  'email' : string,
  'loanType' : LoanType,
  'message' : string,
  'timestamp' : Time,
  'phone' : string,
  'amount' : bigint,
}
export type LoanType = { 'other' : null } |
  { 'auto' : null } |
  { 'home' : null } |
  { 'education' : null } |
  { 'personal' : null } |
  { 'business' : null };
export type Time = bigint;
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getAllContactSubmissions' : ActorMethod<[], Array<ContactSubmission>>,
  'getAllLoanApplications' : ActorMethod<[], Array<LoanApplication>>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getContactSubmission' : ActorMethod<[bigint], ContactSubmission>,
  'getContactSubmissionCount' : ActorMethod<[], bigint>,
  'getLoanApplication' : ActorMethod<[bigint], LoanApplication>,
  'getLoanApplicationCountByType' : ActorMethod<[LoanType], bigint>,
  'getLoanApplicationsByEmail' : ActorMethod<[string], Array<LoanApplication>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'searchContactSubmissionsByName' : ActorMethod<
    [string],
    Array<ContactSubmission>
  >,
  'submitContactForm' : ActorMethod<
    [string, string, string, string],
    { 'id' : bigint, 'timestamp' : Time }
  >,
  'submitLoanApplication' : ActorMethod<
    [string, string, string, LoanType, bigint, string],
    { 'id' : bigint, 'timestamp' : Time }
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];